/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/dashboard.vue')['default']
    EarningChart: typeof import('./src/components/charts/EarningChart.vue')['default']
    LanguageSwitcher: typeof import('./src/components/dashboard/LanguageSwitcher.vue')['default']
    OrderChart: typeof import('./src/components/charts/OrderChart.vue')['default']
    RevenueChart: typeof import('./src/components/charts/RevenueChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesMonth: typeof import('./src/components/charts/SalesMonth.vue')['default']
    SalesYear: typeof import('./src/components/charts/SalesYear.vue')['default']
    StatusChart: typeof import('./src/components/charts/StatusChart.vue')['default']
  }
}
